version: "3"

volumes:
  logs:

services:
  fluentd:
    build: docker/fluentd
    volumes:
      - ./docker/fluentd/:/fluentd/etc
    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - 9200:9200

  kibana:
    image: kibana
    ports:
      - 5601:5601