version: '3'

volumes:
  mysqldata:

services:
  php:
    build: docker/php
    volumes:
      - ./:/var/www/
# TODO: Learn how to separate yml
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: 127.0.0.1:24224
#        tag: php

  mysqlserver:
    image: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "33060:3306"

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    command: nginx -g 'daemon off';

  composer:
    image: "composer"
    volumes:
      - ".:/app"
    command: install